### ISSUE TITLE
Newtonsoft versions > 8.0.2 not supported

### ISSUE THREAD

**Issue by Prosserc** [wbish/jsondiffpatch.net#10]
The nuspec file suggests that this library supports any Newtonsoft version >= 8.0.2. However, because the .csproj file references the version this does not currently work if you have a later version of Newtonsoft.

I would suggest fixing this by either changing the *.csproj files replacing 

`<Reference Include="Newtonsoft.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed, processorArchitecture=MSIL">`

with

`<Reference Include="Newtonsoft.Json, Culture=neutral">`.

Alternatively, if you just changed the nuspec file to say that version 8.0.2 is required then this would at least make it clear that only version 8.0.2 is supported. To change this you could update the .nuspec file replacing `<dependency id="Newtonsoft.Json" version="8.0.2" />` with `<dependency id="Newtonsoft.Json" version="[8.0.2]" />`.

I'm happy to open a pull request for this if it helps, but would like clarification on which approach to take.

**Comment by wbish** [comment]
Seems to work fine for me with Newtonsoft.Json 9.0.0.0.  

Can you share a project with a repro showing the error you are getting?

[PackageVersioning.zip](https://github.com/wbish/jsondiffpatch.net/files/818122/PackageVersioning.zip)
