### ISSUE TITLE
Add support for .NET Standard

### ISSUE THREAD

**Issue by cmeeren** [wbish/jsondiffpatch.net#12]
This is just what I need. Unfortunately, I need it for .NET Standard. Could you make it compatible with .NET Standard?

**Comment by wbish** [comment]
Check out v2.0.0.0 of the nuget package. That should help you out.

**Comment by danielcrenna** [comment]
As per my PR, this does not actually provide .NET Standard support, it provides .NET Standard libraries mixed with .NET 4.5 dependencies, making it require the full framework and not able to be used in pure .NET Core solutions (i.e. Linux & macOS).
