### ISSUE TITLE
Unpatch throws exception

### ISSUE THREAD

**Issue by npfrizze** [wbish/jsondiffpatch.net#16]
Using the attached files, I am unable to 'Unpatch' a file.  While the json is fairly complex, the changes are not that complex.  Is this a bug?

exception - **Index is equal to or greater than Count.
Parameter name: index**

string modifiedJson = File.ReadAllText($"c:/temp/modified.json");
string defaultJson = File.ReadAllText($"c:/temp/default.json");

JsonDiffPatch jsonDiffPatch = new JsonDiffPatch();
var patch = jsonDiffPatch.Diff(modifiedJson, defaultJson);

Console.WriteLine("patch" + patch);

try
{
  string patched = jsonDiffPatch.Unpatch(defaultJson, patch);
  Console.WriteLine("patched" + patched);
}
catch (Exception ex)
{
  Console.WriteLine("exception" + ex.Message);
}
[default.txt](https://github.com/wbish/jsondiffpatch.net/files/1483874/default.txt)
[modified.txt](https://github.com/wbish/jsondiffpatch.net/files/1483875/modified.txt)

**Comment by wbish** [comment]
Yes, definitely a bug. Thanks for reporting. I can confirm I am able to repro it. I will try to get a fix published tonight to nuget.

**Comment by npfrizze** [comment]
I am also seeing an issue with these 2 files.  
It doesn't throw an exception, but the unpatched file is not correct.

[modified.txt](https://github.com/wbish/jsondiffpatch.net/files/1483947/modified.txt)
[default.txt](https://github.com/wbish/jsondiffpatch.net/files/1483948/default.txt)

**Comment by wbish** [comment]
@npfrizze 2.02.0 has been published to nuget with fixes for both issues.
