### ISSUE TITLE
compare only keys

### ISSUE THREAD

**Issue by jmls** [wbish/jsondiffpatch.net#21]
is it possible to compare 2 json objects and only compare the key names, rather than the values ?

for example

```
var a = { foo: 'bar', baz:true}
var b = { foo: 'boo', bingo:false}

```
if I compare b with a, I would like to get that baz has been added, bingo removed and ignore foo

in this event, I want b to end up being 

`{ foo: 'boo', baz:true }`

**Comment by wbish** [comment]
Thanks for the question, @jmls. I've opened #23 to track the ability to support this.
