### ISSUE TITLE
Method not found on versions 2.0.2 and 2.1.0

### ISSUE THREAD

**Issue by nstubi** [wbish/jsondiffpatch.net#24]
Hello,

I've recently upgraded the package. The version 2.0.1 was working like a charm.

The 2.1.0 fails this this error:

Failed: System.MissingMethodException: Method not found: 'Newtonsoft.Json.Linq.JToken JsonDiffPatchDotNet.JsonDiffPatch.Diff(Newtonsoft.Json.Linq.JToken, Newtonsoft.Json.Linq.JToken)'.
System.MissingMethodException
Method not found: 'Newtonsoft.Json.Linq.JToken JsonDiffPatchDotNet.JsonDiffPatch.Diff(Newtonsoft.Json.Linq.JToken, Newtonsoft.Json.Linq.JToken)'.
   at TestsHelpers.TestsHelper.CompareTwoFiles(String expectedFileName, String resultFilePath)
...

The 2.0.2 as well. Apparently, the 2.0.1 is not available anymore.

Please help,

Regards,
Nicolas

**Comment by wbish** [comment]
Hi @nstubi, what version of Newtonsoft.Json are you using?

**Comment by wbish** [comment]
I'm going to close this out. I've tested this several times and haven't seen this issue.

**Comment by auxioruben** [comment]
I just came across the same issue using v2.1.0 of this library with Newtonsoft.Json 11.0.2 and Newtonsoft.Json 12.0.1.  I downgraded to Newtonsoft.Json v10.0.3 and it works with no problems
