### ISSUE TITLE
Implement new Formatters for the Diff output

### ISSUE THREAD

**Issue by pascalsz** [wbish/jsondiffpatch.net#27]
Hi Team,

thanks for sharing this awesome libary.
Is it somehow possible to add some more formatters to the diff output?

I would like to the to the user, what has changed... right now it is very obfuscated. 

as we can see here:
https://benjamine.github.io/jsondiffpatch/demo/index.html
https://github.com/benjamine/jsondiffpatch/blob/master/docs/formatters.md

**Comment by os1r1s110** [comment]
That would effectively be awesome

**Comment by wbish** [comment]
The base class for this has been implemented by #36
