### ISSUE TITLE
When arrays are same, diff is stil non-null

### ISSUE THREAD

**Issue by j-maly** [wbish/jsondiffpatch.net#3]
Hi, when I compare two same arrays, I still get a non-null diff object.

When comparing these two objects: 
{{
  "@context": [
    "http://www.w3.org/ns/csvw",
    {
      "@language": "en",
      "@base": "http://example.org"
    }
  ]
}}

{{
  "@context": [
    "http://www.w3.org/ns/csvw",
    {
      "@language": "en",
      "@base": "http://example.org"
    }
  ]
}}

diff = jdp.Diff(expected, actual) returns 
{{
  "@context": {
    "_t": "a"
  }
}}

I believe the result should be null in this case.

**Comment by wbish** [comment]
Good bug. Thank you for reporting. I'll have a fix ready shortly.
