### ISSUE TITLE
2 Deletions in an array show deletion of a block and addition of a second

### ISSUE THREAD

**Issue by qstevens** [wbish/jsondiffpatch.net#31]
I have a long list of string and deletions of two elements spaced about 10 or so apart results in a diff showing a deletion of a whole chunk followed by the addition of all the elements in between the deleted elements. Is this the intended output, if so, is there a setting that can turn this off?

**Comment by wbish** [comment]
Yeah, this is a known issue. We need to implement #14. Please let me know if you are interested in implementing it.
