### ISSUE TITLE
Can we have new and old values separated out separately without traversing the Diff elements one by one?

### ISSUE THREAD

**Issue by SubasishMohapatra** [wbish/jsondiffpatch.net#38]
Is there an easy way to split old and new values  may be as a part of a property after "Diff"?

**Comment by wbish** [comment]
The diff output is standardized and meant to be compatible with benjamine/jsondiffpatch so changing that is a non starter. 

I think you have two options:

1) write your own diff output parser
2) implement your own delta formatter, e.g: https://github.com/wbish/jsondiffpatch.net/blob/master/Src/JsonDiffPatchDotNet/Formatters/JsonPatch/JsonDeltaFormatter.cs
